title: Marc Ackermann
author:
  name: Marc Ackermann
  email: email@marcackermann.nl
description: >
  ğŸ“ Weblogger ğŸ“· Photographer ğŸ’» Prutser

collections:
  posts:
    output          : true
    permalink: /blog/:title:output_ext

excerpt_separator: <!--more-->
show_drafts: false

# Build settings
baseurl: /
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
